version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: tradingbot-grafana-simple
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_USERS_ALLOW_SIGN_UP: false
      GF_ANALYTICS_REPORTING_ENABLED: false
      GF_ANALYTICS_CHECK_FOR_UPDATES: false
      GF_SECURITY_DISABLE_GRAVATAR: true
      GF_SNAPSHOTS_EXTERNAL_ENABLED: false
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - tradingbot_default

networks:
  tradingbot_default:
    external: true

volumes:
  grafana_data:
