global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: 'tradingbot-monitor'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  - job_name: 'tradingbot-app'
    static_configs:
      - targets: ['localhost:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s
    honor_labels: true
    params:
      format: ['prometheus']

  - job_name: 'tradingbot-health'
    static_configs:
      - targets: ['localhost:5000']
    metrics_path: '/health'
    scrape_interval: 15s
    scrape_timeout: 5s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['localhost:6379']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['localhost:5432']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

